<x-layout>
    <x-slot:title>Lessons</x-slot:title>
    <table>
        <tr>
            <th>ID</th>
            <th>Form</th>
            <th>Teacher</th>
            <th>Subject</th>
            <th>Weekday</th>
            <th>Period</th>
        </tr>
        @foreach ($lessons as $lesson)
            <tr>
                <td>{{$lesson['id']}}</td>
                <td>{{$lesson->form->name}}</td>
                <td>{{$lesson->user->last_name}}</td>
                <td>{{$lesson->subject->name}}</td>
                <td>{{$lesson['weekday']}}</td>
                <td>{{$lesson['period']}}</td>
            </tr>
        @endforeach
    </table>
</x-layout>